version: 1
policy:
  pullRequests: public
tasks:
  $let:
    # Github events have this stuff in different places...
    repo_url: {$if: 'tasks_for == "github-push"',
               then: '${event.repository.clone_url}',
               # Assume Pull Request
               else: '${event.pull_request.head.repo.clone_url}'}
    head_sha: {$if: 'tasks_for == "github-push"',
               then: '${event.after}',
               # Assume Pull Request
               else: '${event.pull_request.head.sha}'}
    owner_email: {$if: 'tasks_for == "github-push"',
                  then: '${event.pusher.email}',
                  # Assume Pull Request
                  else: '${event.pull_request.user.login}@users.noreply.github.com'}
  in:
    # map tox command -> docker image
    $map: [['pypy', 'pypy:3'],
           ['py38', 'python:3.8'], ['py39', 'python:3.9'],
           ['py310', 'python:3.10'], ['py311', 'python:3.11'],
           ['py312', 'python:3.12'], ['check', 'python:3.8']]
    each(py):
      taskId: "${as_slugid(py[0])}"
      provisionerId: "proj-releng"
      workerType: "ci"
      created: {$eval: 'now'}
      deadline: {$fromNow: '1 hour'}
      payload:
        maxRunTime: 1200
        image: {$eval: 'py[1]'}
        command:
          - "/bin/bash"
          - "-c"
          - "git clone ${repo_url} redo && cd redo && git checkout ${head_sha} && pip install tox && tox -e ${py[0]}"
      metadata:
        name: Redo Pull Request ${py[0]}
        description: Pull Request ${py[0]}
        owner: ${owner_email}
        source: "${repo_url}"
